import type { CommandStep } from "@/lib/project-setup/types";

/** Post-V1: generate setup.ps1 for visible terminal mode */
export function generateSetupScript(commands: CommandStep[]): string {
  const lines = [
    "$ErrorActionPreference = 'Stop'",
    "# Generated by AgentHub Dev Scaffold Agent",
    "",
  ];
  for (const cmd of commands) {
    lines.push(`Write-Host "> ${cmd.label}"`);
    if (cmd.cwd) {
      lines.push(`Set-Location -LiteralPath "${cmd.cwd.replace(/"/g, '`"')}"`);
    }
    const argStr = [cmd.exe, ...cmd.args].map((a) => `"${a.replace(/"/g, '`"')}"`).join(" ");
    lines.push(`& ${argStr}`);
    lines.push("");
  }
  return lines.join("\n");
}
