import type { Finding, JmxInventory } from "@/lib/types";

/** Built-in rule templates — used when AI Recommendation Mode is disabled */
export const RULE_TEMPLATES: Record<
  string,
  Omit<Finding, "findingCode"> & { findingCodePrefix: string }
> = {
  "JMX-001": {
    ruleId: "JMX-001",
    findingCodePrefix: "JMX",
    severity: "low",
    category: "Structure",
    element: "Test Plan",
    issue: "Test Plan name is generic or not descriptive.",
    impact: "Hard to identify scenario purpose in BlazeMeter reports and team collaboration.",
    recommendation: "Rename the Test Plan to reflect the business scenario, e.g. Checkout_Load_100Users.",
    whyItMatters: "Clear naming improves traceability across load test runs and release gates.",
  },
  "JMX-002": {
    ruleId: "JMX-002",
    findingCodePrefix: "JMX",
    severity: "medium",
    category: "Structure",
    element: "Thread Group",
    issue: "Thread Group uses a generic default name.",
    impact: "Scenario purpose is unclear in distributed execution and reporting.",
    recommendation: 'Rename Thread Group to match workload, e.g. "Checkout_Load_100Users".',
    whyItMatters: "Performance engineers need scenario-level clarity when triaging failures.",
  },
  "JMX-003": {
    ruleId: "JMX-003",
    findingCodePrefix: "JMX",
    severity: "high",
    category: "Performance / Timers",
    element: "Test Plan",
    issue: "No timers found in the script.",
    impact: "Virtual users may send requests back-to-back without realistic think time, overloading the application.",
    recommendation: "Add Uniform Random Timer (2–5 seconds) between major business steps.",
    whyItMatters: "Load tests without pacing often produce unrealistic traffic spikes and invalid baselines.",
    fixPatternCurrent: "No timer between HTTP samplers",
    fixPatternRecommended: "Uniform Random Timer: 2000ms offset, 3000ms random delay",
  },
  "JMX-004": {
    ruleId: "JMX-004",
    findingCodePrefix: "JMX",
    severity: "high",
    category: "Validation",
    element: "Test Plan",
    issue: "No response assertions found in the script.",
    impact: "HTTP 200 responses may be marked successful even when business logic fails.",
    recommendation: "Add Response Assertion or JSON Assertion on critical samplers (login, checkout, payment).",
    whyItMatters: "Assertions are required to detect functional failures during load execution.",
  },
  "JMX-005": {
    ruleId: "JMX-005",
    findingCodePrefix: "JMX",
    severity: "medium",
    category: "Validation",
    element: "HTTP Sampler",
    issue: "One or more HTTP samplers appear to lack dedicated assertions.",
    impact: "Business-level failures may go undetected under load.",
    recommendation: "Add assertions validating response code, body text, or JSON fields per sampler.",
    whyItMatters: "Critical transactions need explicit pass/fail criteria beyond HTTP status.",
  },
  "JMX-006": {
    ruleId: "JMX-006",
    findingCodePrefix: "JMX",
    severity: "high",
    category: "BlazeMeter Readiness",
    element: "View Results Tree",
    issue: "View Results Tree or heavy GUI listener is enabled.",
    impact: "Consumes memory and can distort performance results during load execution.",
    recommendation: "Disable View Results Tree before BlazeMeter execution. Use Simple Data Writer or Backend Listener.",
    whyItMatters: "GUI listeners are for debugging only, not production load runs.",
  },
  "JMX-007": {
    ruleId: "JMX-007",
    findingCodePrefix: "JMX",
    severity: "critical",
    category: "Data Files",
    element: "CSV Data Set Config",
    issue: "Local absolute file path detected in script.",
    impact: "Script will fail in BlazeMeter cloud execution where local paths are unavailable.",
    recommendation: "Use relative paths (e.g. data/users.csv) and upload CSV as BlazeMeter test assets.",
    whyItMatters: "Cloud runners cannot access developer machine filesystem paths.",
  },
  "JMX-008": {
    ruleId: "JMX-008",
    findingCodePrefix: "JMX",
    severity: "medium",
    category: "Environment",
    element: "HTTP Request",
    issue: "Hardcoded base URL or host detected.",
    impact: "Script is tied to one environment and harder to promote across QA/UAT/Prod.",
    recommendation: "Externalize base URL using ${__P(baseUrl)} or User Defined Variables.",
    whyItMatters: "Environment portability is required for CI/CD and multi-stage testing.",
  },
  "JMX-009": {
    ruleId: "JMX-009",
    findingCodePrefix: "JMX",
    severity: "critical",
    category: "Correlation / Security",
    element: "HTTP Header Manager",
    issue: "Hardcoded Bearer token found in Authorization header.",
    impact: "Token will expire causing false failures; credentials may be exposed in version control.",
    recommendation: "Extract access_token from login response using JSON Extractor and use ${access_token}.",
    whyItMatters: "Hardcoded tokens break correlation and create security compliance risks.",
    fixPatternCurrent: 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
    fixPatternRecommended: "Authorization: Bearer ${access_token}",
  },
  "JMX-010": {
    ruleId: "JMX-010",
    findingCodePrefix: "JMX",
    severity: "critical",
    category: "Security",
    element: "HTTP Authorization Manager",
    issue: "Hardcoded password or secret detected.",
    impact: "Security risk and poor maintainability; secrets may leak in repositories.",
    recommendation: "Move credentials to CSV, environment variables, or BlazeMeter secret store.",
    whyItMatters: "Secrets in scripts violate security policies and audit requirements.",
  },
  "JMX-011": {
    ruleId: "JMX-011",
    findingCodePrefix: "JMX",
    severity: "medium",
    category: "Parameterization",
    element: "CSV Data Set Config",
    issue: "No CSV Data Set Config found for user/data parameterization.",
    impact: "Virtual users may share the same account causing locking and unrealistic behavior.",
    recommendation: "Add CSV Data Set Config with unique users for login and business data.",
    whyItMatters: "Unique test data is essential for realistic concurrent user simulation.",
  },
  "JMX-012": {
    ruleId: "JMX-012",
    findingCodePrefix: "JMX",
    severity: "medium",
    category: "Maintainability",
    element: "Test Plan",
    issue: "Disabled elements found in script.",
    impact: "Dead code increases maintenance burden and may confuse reviewers.",
    recommendation: "Remove or archive disabled samplers and controllers before baseline execution.",
    whyItMatters: "Clean scripts reduce review time and execution surprises.",
  },
  "JMX-013": {
    ruleId: "JMX-013",
    findingCodePrefix: "JMX",
    severity: "high",
    category: "Structure",
    element: "Transaction Controller",
    issue: "No Transaction Controllers wrapping business flows.",
    impact: "BlazeMeter reports lack business-level transaction grouping.",
    recommendation: "Wrap login, browse, cart, and checkout flows in named Transaction Controllers.",
    whyItMatters: "Transaction boundaries align metrics with business KPIs.",
  },
  "JMX-014": {
    ruleId: "JMX-014",
    findingCodePrefix: "JMX",
    severity: "high",
    category: "Web Session",
    element: "HTTP Cookie Manager",
    issue: "Missing HTTP Cookie Manager for web application test.",
    impact: "Session cookies may not propagate correctly across requests.",
    recommendation: "Add HTTP Cookie Manager at Thread Group level for web scenarios.",
    whyItMatters: "Web apps rely on cookie-based sessions for authenticated flows.",
  },
  "JMX-015": {
    ruleId: "JMX-015",
    findingCodePrefix: "JMX",
    severity: "medium",
    category: "Headers",
    element: "HTTP Header Manager",
    issue: "Missing HTTP Header Manager.",
    impact: "Content-Type and auth headers may be inconsistent across samplers.",
    recommendation: "Add HTTP Header Manager with standard headers at Thread Group level.",
    whyItMatters: "Centralized headers reduce duplication and configuration drift.",
  },
  "JMX-016": {
    ruleId: "JMX-016",
    findingCodePrefix: "JMX",
    severity: "high",
    category: "Correlation",
    element: "Extractors",
    issue: "Dynamic values detected but insufficient extractors configured.",
    impact: "Script may fail when session tokens or IDs change between runs.",
    recommendation: "Add JSON Extractor or Regex Extractor for tokens, CSRF, and session IDs.",
    whyItMatters: "Correlation is required for stateful application load testing.",
  },
  "JMX-017": {
    ruleId: "JMX-017",
    findingCodePrefix: "JMX",
    severity: "high",
    category: "Load Config",
    element: "Thread Group",
    issue: "Duration or loop configuration may be unclear for controlled load.",
    impact: "Risk of uncontrolled or accidentally infinite test execution.",
    recommendation: "Set explicit duration in Thread Group scheduler or define finite loop count.",
    whyItMatters: "Controlled duration is required for baseline and soak test planning.",
  },
  "JMX-018": {
    ruleId: "JMX-018",
    findingCodePrefix: "JMX",
    severity: "medium",
    category: "Plugins",
    element: "Test Plan",
    issue: "Custom plugin elements detected — verify BlazeMeter compatibility.",
    impact: "Unsupported plugins may fail in cloud execution.",
    recommendation: "Document plugin dependencies and confirm BlazeMeter support before upload.",
    whyItMatters: "Cloud environments may not include all JMeter plugins from local installs.",
  },
  "JMX-019": {
    ruleId: "JMX-019",
    findingCodePrefix: "JMX",
    severity: "medium",
    category: "Environment",
    element: "User Defined Variables",
    issue: "Environment values do not appear fully externalized.",
    impact: "Promoting script across environments requires manual edits.",
    recommendation: "Use properties file or ${__P()} for protocol, host, port, and credentials.",
    whyItMatters: "Externalized config enables one script for QA, UAT, and production-like stages.",
  },
  "JMX-020": {
    ruleId: "JMX-020",
    findingCodePrefix: "JMX",
    severity: "medium",
    category: "Debug",
    element: "Debug Sampler / Listener",
    issue: "Debug elements or non-essential listeners may be enabled.",
    impact: "Adds overhead and noise during load execution.",
    recommendation: "Disable debug samplers and non-essential listeners before BlazeMeter run.",
    whyItMatters: "Debug tooling skews resource usage under load.",
  },
};

export function enrichFinding(
  template: (typeof RULE_TEMPLATES)[string],
  inventory: JmxInventory,
  index: number
): Finding {
  const code = `${template.findingCodePrefix}-${String(index + 1).padStart(3, "0")}`;
  let element = template.element;
  let detectedValue = template.detectedValue;
  let locationPath = `Test Plan: ${inventory.testPlanName}`;

  if (template.ruleId === "JMX-005" && inventory.details.samplersWithoutAssertion[0]) {
    element = inventory.details.samplersWithoutAssertion[0];
    locationPath += ` > Thread Group > ${element}`;
  }
  if (template.ruleId === "JMX-007" && inventory.details.localPathExamples[0]) {
    detectedValue = inventory.details.localPathExamples[0];
  }
  if (template.ruleId === "JMX-009" && inventory.details.bearerTokenSnippet) {
    detectedValue = inventory.details.bearerTokenSnippet;
    locationPath += " > HTTP Header Manager > Authorization";
  }

  return {
    ruleId: template.ruleId,
    findingCode: code,
    severity: template.severity,
    category: template.category,
    element,
    issue: template.issue,
    impact: template.impact,
    recommendation: template.recommendation,
    whyItMatters: template.whyItMatters,
    detectedValue,
    locationPath,
    codeSnippet: detectedValue,
    fixPatternCurrent: template.fixPatternCurrent,
    fixPatternRecommended: template.fixPatternRecommended,
    tags: [template.category],
  };
}
