import type { ReadinessStatus } from "@/lib/types";
import { readinessLabel } from "@/lib/utils";

export interface ReportData {
  scriptName: string;
  externalReviewId?: string | null;
  reviewDate: string;
  score: number;
  readiness: ReadinessStatus | string | null;
  executiveSummary: string | null;
  inventory: Record<string, number> | null;
  topRisks: string[];
  fixOrder: string[];
  aiMode: string;
  findings: {
    rule_id: string;
    finding_code?: string | null;
    severity: string;
    category?: string | null;
    element?: string | null;
    issue: string;
    impact?: string | null;
    recommendation?: string | null;
  }[];
}

function groupFindings(findings: ReportData["findings"]) {
  return {
    critical: findings.filter((f) => f.severity === "critical"),
    high: findings.filter((f) => f.severity === "high"),
    medium: findings.filter((f) => f.severity === "medium"),
    low: findings.filter((f) => f.severity === "low"),
  };
}

export function generateMarkdownReport(data: ReportData): string {
  const g = groupFindings(data.findings);
  const inv = data.inventory;
  const readiness = data.readiness
    ? readinessLabel(String(data.readiness))
    : "Unknown";

  let md = `# JMeter Script Review Report\n\n`;
  md += `| Field | Value |\n|-------|-------|\n`;
  md += `| Script | ${data.scriptName} |\n`;
  md += `| Review ID | ${data.externalReviewId ?? "-"} |\n`;
  md += `| Date | ${data.reviewDate} |\n`;
  md += `| Reviewer | Script Review Agent (Rule-based v1) |\n`;
  md += `| AI Mode | ${data.aiMode === "disabled" ? "Disabled (templates)" : data.aiMode} |\n`;
  md += `| Score | **${data.score}/100** |\n`;
  md += `| Readiness | **${readiness}** |\n\n`;

  md += `## Executive Summary\n\n${data.executiveSummary ?? "-"}\n\n`;

  if (inv) {
    md += `## Inventory Snapshot\n\n`;
    md += `- Thread Groups: ${inv.threadGroups ?? 0}\n`;
    md += `- HTTP Samplers: ${inv.httpSamplers ?? 0}\n`;
    md += `- Assertions: ${inv.assertions ?? 0}\n`;
    md += `- Timers: ${inv.timers ?? 0}\n`;
    md += `- CSV Data Sets: ${inv.csvDataSets ?? 0}\n`;
    md += `- Extractors: ${inv.extractors ?? 0}\n`;
    md += `- Listeners: ${inv.listeners ?? 0}\n`;
    md += `- Disabled Elements: ${inv.disabledElements ?? 0}\n\n`;
  }

  const sections = [
    ["Critical Findings", g.critical],
    ["High Findings", g.high],
    ["Medium Findings", g.medium],
    ["Low Findings", g.low],
  ] as const;

  for (const [title, list] of sections) {
    if (!list.length) continue;
    md += `## ${title} (${list.length})\n\n`;
    list.forEach((f, i) => {
      md += `### ${i + 1}. ${f.issue}\n`;
      md += `- **Rule:** ${f.rule_id} | **Severity:** ${f.severity}\n`;
      md += `- **Element:** ${f.element ?? "-"}\n`;
      if (f.impact) md += `- **Impact:** ${f.impact}\n`;
      if (f.recommendation) md += `- **Recommendation:** ${f.recommendation}\n`;
      md += `\n`;
    });
  }

  if (data.topRisks.length) {
    md += `## Top Risks\n\n`;
    data.topRisks.forEach((r, i) => {
      md += `${i + 1}. ${r}\n`;
    });
    md += `\n`;
  }

  if (data.fixOrder.length) {
    md += `## Recommended Fix Order\n\n`;
    data.fixOrder.forEach((item) => {
      md += `- ${item}\n`;
    });
    md += `\n`;
  }

  md += `## Final Recommendation\n\n`;
  if (data.score >= 70) {
    md += `Script may proceed to BlazeMeter with noted fixes.\n`;
  } else {
    md += `Do not execute for baseline load testing until Critical and High findings are resolved.\n`;
  }

  md += `\n---\n*Generated by Agent Hub · Rule-based Engine v1*\n`;
  return md;
}

export function generateHtmlReport(data: ReportData): string {
  const md = generateMarkdownReport(data);
  const escaped = md
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\n\n/g, "</p><p>")
    .replace(/\n/g, "<br/>");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>Review Report: ${data.scriptName}</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; color: #0f172a; line-height: 1.6; }
    h1 { color: #1d4ed8; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.5rem; }
    h2 { margin-top: 2rem; color: #334155; }
    h3 { color: #475569; }
    table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
    td, th { border: 1px solid #e2e8f0; padding: 8px; text-align: left; }
    .meta { background: #f8fafc; padding: 1rem; border-radius: 8px; margin-bottom: 1.5rem; }
    @media print { body { margin: 0; } }
  </style>
</head>
<body>
  <div class="meta"><strong>Agent Hub</strong> - JMeter Script Review Report</div>
  <div>${escaped}</div>
</body>
</html>`;
}

export function generateJsonReport(data: ReportData): string {
  return JSON.stringify(
    {
      version: "1.0",
      engine: "rule-based",
      aiRecommendationMode: data.aiMode,
      generatedAt: new Date().toISOString(),
      ...data,
    },
    null,
    2
  );
}

export function downloadBlob(content: string, fileName: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(url);
}

export function printHtmlReport(html: string) {
  const win = window.open("", "_blank");
  if (!win) {
    alert("Please allow pop-ups to export PDF via print.");
    return;
  }
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 500);
}
