import type { FileTemplate, ProjectSetupConfig } from "@/lib/project-setup/types";
import { installLatestArgs } from "@/lib/project-setup/templates/package-latest";
import { frontendRelPrefix } from "@/lib/project-setup/templates/shared";

export function usesMui(config: ProjectSetupConfig): boolean {
  return config.styling === "mui";
}

/** True when create-next-app / Vite scaffolds include Tailwind CSS. */
export function usesTailwindStyling(config: ProjectSetupConfig): boolean {
  return config.styling === "tailwind" || config.styling === "shadcn";
}

export function muiNextThemeFiles(rel: string): FileTemplate[] {
  return [
    {
      relativePath: `${rel}src/theme/theme.ts`,
      content: `"use client";

import { createTheme } from "@mui/material/styles";

export const theme = createTheme({
  cssVariables: true,
  typography: {
    fontFamily: "var(--font-geist-sans), Roboto, Helvetica, Arial, sans-serif",
  },
});
`,
    },
    {
      relativePath: `${rel}src/app/ThemeRegistry.tsx`,
      content: `"use client";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import CssBaseline from "@mui/material/CssBaseline";
import { ThemeProvider } from "@mui/material/styles";
import { theme } from "@/theme/theme";

export default function ThemeRegistry({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AppRouterCacheProvider>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        {children}
      </ThemeProvider>
    </AppRouterCacheProvider>
  );
}
`,
    },
    {
      relativePath: `${rel}src/app/globals.css`,
      writePhase: "post",
      content: `html,
body {
  max-width: 100vw;
  min-height: 100%;
}

body {
  margin: 0;
}
`,
    },
  ];
}

export function muiNextLayoutInner(config: ProjectSetupConfig, childrenExpr: string): string {
  let inner = childrenExpr;
  if (config.stateManagement === "context") {
    inner = `<CounterProvider>${inner}</CounterProvider>`;
  }
  if (config.stateManagement === "redux") {
    inner = `<StoreProvider>${inner}</StoreProvider>`;
  }
  if (!usesTailwindStyling(config)) {
    inner = `<ThemeRegistry>${inner}</ThemeRegistry>`;
  }
  return inner;
}

export function muiNextLayoutImports(config: ProjectSetupConfig): string {
  const lines: string[] = [];
  if (config.stateManagement === "redux") {
    lines.push(`import StoreProvider from "./StoreProvider";`);
  }
  if (config.stateManagement === "context") {
    lines.push(`import { CounterProvider } from "@/lib/context/counter/CounterProvider";`);
  }
  if (!usesTailwindStyling(config)) {
    lines.push(`import ThemeRegistry from "./ThemeRegistry";`);
  }
  return lines.length ? `${lines.join("\n")}\n` : "";
}

export function muiInstallArgs(): string[] {
  return installLatestArgs(
    "@mui/material",
    "@mui/material-nextjs",
    "@emotion/react",
    "@emotion/styled",
  );
}

export function nextPageCenterShell(config: ProjectSetupConfig, body: string): string {
  if (!usesTailwindStyling(config)) {
    return `<Box
      component="main"
      sx={{
        minHeight: "100vh",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        gap: 2,
        p: 4,
      }}
    >
      ${body}
    </Box>`;
  }
  return `<main className="flex min-h-svh flex-col items-center justify-center gap-4 p-8">
      ${body}
    </main>`;
}

export function nextHomePageContent(
  config: ProjectSetupConfig,
  counterImport: string,
): string {
  const muiImport = !usesTailwindStyling(config) ? 'import Box from "@mui/material/Box";\n' : "";
  return `${muiImport}import { Counter } from "${counterImport}";

export default function Home() {
  return (
    ${nextPageCenterShell(config, "<Counter />")}
  );
}
`;
}

export function buildNextRootLayout(
  config: ProjectSetupConfig,
  innerChildrenExpr: string,
  additionalImports = "",
): string {
  const extraImports = `${muiNextLayoutImports(config)}${additionalImports ? `${additionalImports}\n` : ""}`;
  const inner = muiNextLayoutInner(config, innerChildrenExpr);
  const bodyClass = !usesTailwindStyling(config)
    ? "`${geistSans.variable} ${geistMono.variable}`"
    : "`${geistSans.variable} ${geistMono.variable} antialiased`";

  return `import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
${extraImports}
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "${config.projectName}",
  description: "Generated by AgentHub Project Setup Agent",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={${bodyClass}}>
        ${inner}
      </body>
    </html>
  );
}
`;
}
