import type { ProjectSetupConfig } from "@/lib/project-setup/types";

export function scopeIncludesFrontend(config: ProjectSetupConfig): boolean {
  return config.projectScope === "frontend_only" || config.projectScope === "full_stack";
}

export function scopeIncludesBackend(config: ProjectSetupConfig): boolean {
  return config.projectScope === "backend_only" || config.projectScope === "full_stack";
}

export function usesPrismaBackend(config: ProjectSetupConfig): boolean {
  return scopeIncludesBackend(config) && config.database === "postgresql";
}

export function usesJwtAuth(config: ProjectSetupConfig): boolean {
  return config.backendAuth === "jwt" || config.frontendAuth === "jwt";
}

export function shouldRunPrismaMigrate(config: ProjectSetupConfig): boolean {
  return (
    usesPrismaBackend(config) &&
    config.runMigrations &&
    Boolean(config.databaseUrl?.trim())
  );
}

export function backendEnvRel(config: ProjectSetupConfig): string {
  return config.projectScope === "backend_only" ? ".env" : "backend/.env";
}

export function hasBackendEnvValues(config: ProjectSetupConfig): boolean {
  return Boolean(config.databaseUrl?.trim() || config.jwtSecret?.trim());
}

/** Env vars for backend setup commands (Prisma migrate dev, etc.). */
export function backendCommandEnv(config: ProjectSetupConfig): Record<string, string> | undefined {
  const env: Record<string, string> = {};
  if (config.databaseUrl?.trim()) env.DATABASE_URL = config.databaseUrl.trim();
  if (config.jwtSecret?.trim()) env.JWT_SECRET = config.jwtSecret.trim();
  return Object.keys(env).length > 0 ? env : undefined;
}

export function frontendRelPrefix(config: ProjectSetupConfig): string {
  return config.projectScope === "frontend_only" ? "" : "frontend/";
}

export function readmeContent(config: ProjectSetupConfig): string {
  const lines = [
    `# ${config.projectName}`,
    "",
    config.description || "Generated by AgentHub Project Setup Agent.",
    "",
    "## Scope",
    "",
    config.projectScope.replace(/_/g, " "),
    "",
    "## Getting started",
    "",
  ];

  if (config.projectScope === "backend_only") {
    lines.push(
      "1. Copy `.env.example` to `.env` and fill in values.",
      "2. `npm install` (if not already done by the setup agent).",
      "3. `npm run dev`",
      ""
    );
  } else if (config.projectScope === "frontend_only") {
    lines.push(
      "See the generated frontend app for install and dev commands.",
      ""
    );
  } else {
    lines.push(
      "See the `frontend/` and `backend/` folders for stack-specific commands.",
      ""
    );
  }

  if (usesPrismaBackend(config)) {
    const backendDir = config.projectScope === "backend_only" ? "." : "backend";
    lines.push(
      "## Prisma (PostgreSQL)",
      "",
      "This project was scaffolded with the latest Prisma available at generation time.",
      "Resolved versions are recorded in `package-lock.json` — see `package.json` for what was installed.",
      "",
      "### Requirements",
      "",
      "- Node.js **>= 20.19** (see `engines` in the backend `package.json`)",
      "",
      "### Upgrade Prisma deliberately",
      "",
      `From the \`${backendDir}\` folder:`,
      "",
      "```bash",
      "npm install prisma@latest --save-dev @prisma/client@latest @prisma/adapter-pg@latest",
      "```",
      "",
      "Review the [Prisma upgrade guide](https://www.prisma.io/docs/guides/upgrade-prisma-orm/v7) before major version bumps — config and client setup may change.",
      "",
      "### Database setup",
      "",
      "1. Set `DATABASE_URL` in `.env` (copy from `.env.example`).",
      "2. Run `npx prisma migrate dev` when you are ready to apply migrations (or enable it during setup in the wizard).",
      ""
    );
  }

  return lines.join("\n");
}

export function envExampleContent(config: ProjectSetupConfig): string {
  const lines = ["# Generated by AgentHub Project Setup Agent", ""];
  if (scopeIncludesBackend(config)) {
    lines.push("PORT=4000");
    if (config.database === "postgresql") {
      lines.push(
        `DATABASE_URL="postgresql://user:pass@localhost:5432/mydb"`,
      );
    }
    if (config.database === "mongodb") {
      lines.push("MONGODB_URI=mongodb://localhost:27017/mydb");
    }
  }
  if (config.frontendAuth !== "none" || scopeIncludesBackend(config)) {
    lines.push("", "# Auth");
    if (usesJwtAuth(config)) {
      lines.push(`JWT_SECRET="change-me"`);
    }
    if (config.frontendAuth === "google_oauth" || config.backendAuth === "google_oauth") {
      lines.push("GOOGLE_CLIENT_ID=", "GOOGLE_CLIENT_SECRET=");
    }
  }
  return `${lines.join("\n")}\n`;
}

/** Backend .env written during setup when the user provides credentials. */
export function envFileContent(config: ProjectSetupConfig): string {
  const lines = ["# Generated by AgentHub Project Setup Agent", "", "PORT=4000"];

  if (usesPrismaBackend(config) && config.databaseUrl?.trim()) {
    lines.push(`DATABASE_URL=${config.databaseUrl.trim()}`);
  }

  if (config.database === "mongodb") {
    lines.push(`MONGODB_URI=mongodb://localhost:27017/${slugify(config.projectName)}`);
  }

  if (usesJwtAuth(config) && config.jwtSecret?.trim()) {
    lines.push("", "# Auth", `JWT_SECRET=${config.jwtSecret.trim()}`);
  }

  return `${lines.join("\n")}\n`;
}

/**
 * Turns a free-text project name into a safe identifier for places that
 * can't have spaces, uppercase, or special characters — npm package.json
 * "name" fields, database names, Docker service/container names, etc.
 * Falls back to "app" if the result would otherwise be empty (e.g. the
 * project name was all emoji/symbols).
 */
export function slugify(name: string): string {
  return (
    name
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9-]+/g, "-")
      .replace(/^-+|-+$/g, "") || "app"
  );
}